# ── APLICACIÓN ──────────────────────────────────────────────
spring.application.name=biometrico-umg
server.port=8081
server.address=0.0.0.0

# ── BASE DE DATOS ───────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/biometrico_umg
spring.datasource.username=biometrico_umg_user
spring.datasource.password=TU_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

# ── HIKARI / POOL DE CONEXIONES ─────────────────────────────
spring.datasource.hikari.pool-name=BiometricoPool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepaliveTime=300000
spring.datasource.hikari.leakDetectionThreshold=20000


# ── JPA / HIBERNATE ─────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ── THYMELEAF ───────────────────────────────────────────────
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# ── ARCHIVOS SUBIDOS ─────────────────────────────────────────
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Directorio de fotografias
app.upload.dir=uploads/fotos

# ── CORREO ELECTRÓNICO ───────────────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dcuch1@miumg.edu.gt
spring.mail.password=qajazqjmufhhliir
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# ── LOGS ─────────────────────────────────────────────────────
logging.level.com.umg=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN


#TWILIO

twilio.account.sid=TU_SID
twilio.auth.token=TU_TOKEN
twilio.whatsapp.from=+14155238886
app.base-url= https://stowaway-underfeed-safehouse.ngrok-free.dev

server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.use-forward-headers=true


